### ISSUE TITLE
Task: @rsile25 can we get this repo made public?

### ISSUE THREAD

**Issue by KameronKerger** [DOI-DO/ceq-j40-cejst-2#26]
## Describe the task
Asking @RSile25 to make this repo public so the team can work

## Additional context

* Let me know how I can be helpful

**Comment by RSile25** [comment]
Done ma'am, done


From: Kameron Kerger ***@***.***>
Sent: Thursday, November 21, 2024 1:16 PM
To: DOI-DO/ceq-j40-cejst-2 ***@***.***>
Cc: Sile, Rachel R ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [DOI-DO/ceq-j40-cejst-2] Task: @rsile25 can we get this repo made public? (Issue #26)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Thanks, and yes, we want to open source this repo!

-
