### ISSUE TITLE
Task: Repository admin access for @neilmb

### ISSUE THREAD

**Issue by neilmb** [DOI-DO/ceq-j40-cejst-2#32]
## Describe the task

@RSile25 can you make @neilmb an admin for this repository? I need to be able to see and change repository secrets.

## Acceptance Criteria

- [ ] @neilmb can access the "Settings" tab in this repository

## Additional context

Any other repository admin could add me, so if @vim-usds sees this, he could swoop in and save Rachel the trouble. ;)

**Comment by vim-usds** [comment]
Done!
